name: Deploy Front-end no ECR

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install
        working-directory: client

      - name: Build do projeto
        run: npm run build
        working-directory: client

      - name: Login no Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 727169793826.dkr.ecr.us-east-2.amazonaws.com

      - name: Build da imagem Docker
        run: docker build -t next-front -f client/Dockerfile ./client

      - name: Tag da imagem com o URI do repositório
        run: docker tag next-front:latest 727169793826.dkr.ecr.us-east-2.amazonaws.com/ecommerce/spa:latest

      - name: Push da imagem para o ECR
        run: docker push 727169793826.dkr.ecr.us-east-2.amazonaws.com/ecommerce/spa:latest
